services:
  usm:
    build: .
    container_name: usm
    depends_on: 
      - usm-db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usm-db:5432/usm
      - SPRING_DATASOURCE_USERNAME=usm
      - SPRING_DATASOURCE_PASSWORD=usm
    restart: unless-stopped
  usm-db:
    image: postgres:17-alpine
    container_name: usm-db
    environment:
      - POSTGRES_PASSWORD=usm
      - POSTGRES_USER=usm
      - POSTGRES_DB=usm
    ports:
      - 5432:5432
    restart: unless-stopped