spring:
  application:
    name: usm
  datasource:
    url: jdbc:postgresql://usm-db:5432/usm
    username: usm
    password: usm
  flyway:
    locations: classpath:db/migration
logging:
  file:
    name: ./log/usm.log