spring:
  application:
    name: usm
  datasource:
    url: jdbc:postgresql://localhost:5432/usm
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
  